name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Uploads a Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        path: CommandPlus/bin
    - name: Push Nupkg
      uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
      with:
        nupkg-path: CommandPlus/bin/Debug/*.nupkg
        repo-owner: NoArtifactLights
        gh-user: RelaperCrystal
        token: ${{ secrets.GITHUB_TOKEN }}    
